/**
 * This code was generated by Builder.io.
 */


import React, { useState, useEffect } from "react";
import { Line } from "react-chartjs-2";

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

const DemandForecast = () => {
  const [forecastData, setForecastData] = useState(null);

  useEffect(() => {
    fetchForecastData();
  }, []);

  const fetchForecastData = async () => {
    try {
      const response = await fetch("/api/demand-forecast");
      const data = await response.json();
      setForecastData(data);
    } catch (error) {
      console.error("Error fetching forecast data:", error);
    }
  };

  const chartOptions = {
    responsive: true,
    plugins: {
      legend: {
        position: "top",
      },
      title: {
        display: true,
        text: "Demand Forecast",
      },
    },
  };

  const chartData = {
    labels: forecastData?.dates || [],
    datasets: [
      {
        label: "Forecasted Demand",
        data: forecastData?.forecast || [],
        borderColor: "rgb(53, 162, 235)",
        backgroundColor: "rgba(53, 162, 235, 0.5)",
      },
      {
        label: "Actual Demand",
        data: forecastData?.actual || [],
        borderColor: "rgb(255, 99, 132)",
        backgroundColor: "rgba(255, 99, 132, 0.5)",
      },
    ],
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">Demand Forecast</h2>
      {forecastData ? (
        <Line options={chartOptions} data={chartData} />
      ) : (
        <p>Loading forecast data...</p>
      )}
    </div>
  );
};

export default DemandForecast;
