/**
 * This code was generated by Builder.io.
 */
import React, { useState, useEffect } from "react";

const PredictiveMaintenance = () => {
  const [equipmentStatus, setEquipmentStatus] = useState([]);

  useEffect(() => {
    fetchEquipmentStatus();
  }, []);

  const fetchEquipmentStatus = async () => {
    try {
      const response = await fetch("/api/equipment-status");
      const data = await response.json();
      setEquipmentStatus(data);
    } catch (error) {
      console.error("Error fetching equipment status:", error);
    }
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">Predictive Maintenance</h2>
      <table className="w-full">
        <thead>
          <tr className="bg-gray-200">
            <th className="p-2 text-left">Equipment</th>
            <th className="p-2 text-left">Status</th>
            <th className="p-2 text-left">Next Maintenance</th>
          </tr>
        </thead>
        <tbody>
          {equipmentStatus.map((item) => (
            <tr key={item.id} className="border-b">
              <td className="p-2">{item.name}</td>
              <td className="p-2">
                <span
                  className={`px-2 py-1 rounded ${
                    item.status === "Good"
                      ? "bg-green-200 text-green-800"
                      : "bg-red-200 text-red-800"
                  }`}
                >
                  {item.status}
                </span>
              </td>
              <td className="p-2">{item.nextMaintenance}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default PredictiveMaintenance;
