/**
 * This code was generated by Builder.io.
 */
import React, { useState, useEffect } from "react";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import "leaflet/dist/leaflet.css";

const RouteOptimization = () => {
  const [deliveries, setDeliveries] = useState([]);
  const [optimizedRoute, setOptimizedRoute] = useState([]);

  useEffect(() => {
    fetchDeliveryData();
  }, []);

  const fetchDeliveryData = async () => {
    try {
      const response = await fetch("/api/deliveries");
      const data = await response.json();
      setDeliveries(data);
      optimizeRoute(data);
    } catch (error) {
      console.error("Error fetching delivery data:", error);
    }
  };

  const optimizeRoute = async (deliveryData) => {
    try {
      const response = await fetch("/api/optimize-route", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(deliveryData),
      });
      const optimizedData = await response.json();
      setOptimizedRoute(optimizedData);
    } catch (error) {
      console.error("Error optimizing route:", error);
    }
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">Route Optimization</h2>
      <div className="h-96 mb-4">
        <MapContainer
          center={[51.505, -0.09]}
          zoom={13}
          style={{ height: "100%", width: "100%" }}
        >
          <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
          {optimizedRoute.map((stop, index) => (
            <Marker key={index} position={[stop.lat, stop.lng]}>
              <Popup>
                Stop {index + 1}: {stop.address}
              </Popup>
            </Marker>
          ))}
        </MapContainer>
      </div>
      <div>
        <h3 className="text-xl font-semibold mb-2">Optimized Route:</h3>
        <ol className="list-decimal list-inside">
          {optimizedRoute.map((stop, index) => (
            <li key={index}>{stop.address}</li>
          ))}
        </ol>
      </div>
    </div>
  );
};

export default RouteOptimization;
