/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DemandForecast from "./DemandForecast";
import PredictiveMaintenance from "./PredictiveMaintenance";
import SupplierRiskManagement from "./SupplierRiskManagement";
import RouteOptimization from "./RouteOptimization";
import AnomalyDetection from "./AnomalyDetection";

const SupplyChainDashboard = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Supply Chain ML Dashboard</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <DemandForecast />
        <PredictiveMaintenance />
        <SupplierRiskManagement />
        <RouteOptimization />
        <AnomalyDetection />
      </div>
    </div>
  );
};

export default SupplyChainDashboard;
