/**
 * This code was generated by Builder.io.
 */
import React, { useState, useEffect } from "react";

const SupplierRiskManagement = () => {
  const [suppliers, setSuppliers] = useState([]);

  useEffect(() => {
    fetchSupplierRiskData();
  }, []);

  const fetchSupplierRiskData = async () => {
    try {
      const response = await fetch("/api/supplier-risk");
      const data = await response.json();
      setSuppliers(data);
    } catch (error) {
      console.error("Error fetching supplier risk data:", error);
    }
  };

  const getRiskColor = (riskScore) => {
    if (riskScore < 3) return "bg-green-200 text-green-800";
    if (riskScore < 7) return "bg-yellow-200 text-yellow-800";
    return "bg-red-200 text-red-800";
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">Supplier Risk Management</h2>
      <table className="w-full">
        <thead>
          <tr className="bg-gray-200">
            <th className="p-2 text-left">Supplier</th>
            <th className="p-2 text-left">Risk Score</th>
            <th className="p-2 text-left">Risk Factors</th>
          </tr>
        </thead>
        <tbody>
          {suppliers.map((supplier) => (
            <tr key={supplier.id} className="border-b">
              <td className="p-2">{supplier.name}</td>
              <td className="p-2">
                <span
                  className={`px-2 py-1 rounded ${getRiskColor(
                    supplier.riskScore
                  )}`}
                >
                  {supplier.riskScore}
                </span>
              </td>
              <td className="p-2">{supplier.riskFactors.join(", ")}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default SupplierRiskManagement;
