// // // import React from 'react'
// // // import AnomalyDetection from "./components/AnomalyDetection";
// // // import DemandForecasting from './components/DemandForecasting';
// // // import SupplyChainDashboard from './components/SupplyChainDashboard';
// // // import SupplierRiskManagement from './components/SupplierRiskManagement';
// // // import RouteOptimization from './components/RouteOptimization';
// // // import PredictiveMaintenance from './components/PredictiveMaintenance';

// // // const App = () => {
// // //   return (
// // //     <div>
// // //       <AnomalyDetection />
// // //       <DemandForecasting />
// // //       <SupplyChainDashboard />

// // //       <ImageComponent />
// // //       <RouteOptimization />
// // //       <SupplierRiskManagement />

// // //     </div>
// // //   )
// // // }

// // // export default App

// // /**
// //  * This code was generated by Builder.io.
// //  */

// // import React from "react";
// // import { BrowserRouter as Router, Route, Switch } from "react-router-dom";
// // import LandingPage from "./components/supplyChainOptimization/LandingPage";
// // import SupplyChainDashboard from "./components/supplyChainOptimization/SupplyChainDashboard";

// // function App() {
// //   return (
// //     <Router>
// //       <Switch>
// //         <Route exact path="/" component={LandingPage} />
// //         <Route path="/dashboard" component={SupplyChainDashboard} />
// //       </Switch>
// //     </Router>
// //   );
// // }

// // export default App;


// import React from 'react'
// import Feature from './components/Feature'
// import FeatureSection from './components/FeatureSection';
// import Footer from './components/Footer';
// import Header from './components/Header';
// import Hero from './components/Hero';
// import LandingPage from "./components/LandingPage";
// import PricingSection from './components/PricingSection';


// const App = () => {
//   return (
//     <div>
//       {/* <Feature />
//       <FeatureSection />
//       <Footer />
//       <Header />
//       <Hero /> */}
//       <LandingPage />
//       <PricingSection />

      
//     </div>
//   )
// }

// export default App


import React from 'react'
import SupplyChainDashboard from './components/supplyChainML/SupplyChainDashboard';
import AnomalyDetection from './components/supplyChainML/AnomalyDetection';



const App = () => {
  return (
    <div>
      <SupplyChainDashboard />

      
    </div>
  )
}

export default App
